# CI workflow runs linting, typing, and unit tests on every push to a branch
# and when called from another workflow.
---
name: "CI"
"on":
  workflow_call:
  push:
    branches:
      - "tickets/**"
      - "u/**"
      - "!main"

env:
  UV_FROZEN: "1"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  test:
    name: Run unit tests
    needs: [lint]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Run tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          tox-envs: "py,coverage-report,typing"
          tox-requirements: requirements/tox.txt
